"""
Hunyuan3D mesh generation/rendering, TripoSG mesh backbone, and MVAdapter texturizing.

Classes:
  MeshGenerator        — generate 3D meshes from images via Hunyuan3D-2, with
                         pluggable texturizing backends (Hunyuan paint, MVAdapter).
  Renderer             — render .glb meshes with PyTorch3D.
  TripoSGMeshBackbone  — generate complete watertight meshes (geometry + colour)
                         from a single image via TripoSG (VAST-AI/TripoSG).
                         This is a *mesh backbone* model, not a texturizer — it
                         produces geometry in one forward pass.
  MVAdapterTexturizer  — texturize an existing mesh using MV-Adapter
                         (huanngzh/MV-Adapter) geometry-guided multi-view generation
                         followed by UV-projection. Accepts either a text prompt or
                         a reference image.

Backward compatibility alias:
  TripoSGTexturizer = TripoSGMeshBackbone  (name kept for older import sites)

Install:
    TripoSG:   git clone https://github.com/VAST-AI-Research/TripoSG.git triposg-repo
               export PYTHONPATH=triposg-repo:$PYTHONPATH
    MVAdapter: git clone https://github.com/huanngzh/MV-Adapter.git mvadapter-repo
               pip install -e mvadapter-repo
               pip install git+https://github.com/NVlabs/nvdiffrast.git
               wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth -O checkpoints/RealESRGAN_x2plus.pth
               wget https://github.com/Sanster/models/releases/download/add_big_lama/big-lama.pt -O checkpoints/big-lama.pt

Run final_setup.sh to handle all of the above automatically.
"""

import gc
import os
import sys
import tempfile
import numpy as np
import torch
from PIL import Image

from hy3dgen.shapegen import Hunyuan3DDiTFlowMatchingPipeline
from hy3dgen.texgen import Hunyuan3DPaintPipeline
from pytorch3d.io import IO
from pytorch3d.io.experimental_gltf_io import MeshGlbFormat
from pytorch3d.renderer import (
    BlendParams,
    MeshRasterizer,
    MeshRenderer,
    PerspectiveCameras,
    PointLights,
    RasterizationSettings,
    SoftPhongShader,
)


# ── TripoSGMeshBackbone ───────────────────────────────────────────────────────

class TripoSGMeshBackbone:
    """
    Generates watertight 3D meshes (geometry + per-vertex colour) from a single
    image using TripoSG (VAST-AI/TripoSG).

    TripoSG is a rectified-flow image-to-3D **mesh backbone** model that produces
    complete geometry in one forward pass.  It is *not* a texturizer — it outputs
    raw vertex geometry and optional per-vertex colour rather than UV-mapped
    textures.  Use :class:`MVAdapterTexturizer` to apply a UV texture atlas on top
    of a mesh generated by Hunyuan3D-2 or any other backbone.

    When used as the mesh backbone inside :class:`MeshGenerator`, the returned
    mesh replaces the Hunyuan3D shape-generation step (TripoSG produces geometry
    and vertex colour in one shot).

    The pipeline class ``TripoSGPipeline`` lives in the ``triposg`` package (part
    of the TripoSG GitHub repo) and follows the diffusers interface.

    Install::

        git clone https://github.com/VAST-AI-Research/TripoSG.git triposg-repo
        export PYTHONPATH=triposg-repo:$PYTHONPATH

    Weights are downloaded automatically from ``VAST-AI/TripoSG`` on HuggingFace
    the first time :meth:`load` is called (~8 GB VRAM, ~5 GB disk).

    Example::

        backbone = TripoSGMeshBackbone(device="cuda")
        mesh = backbone.generate(Image.open("object.png"))
        mesh.export("object_triposg.glb")
    """

    HF_MODEL_ID = "VAST-AI/TripoSG"
    DEFAULT_WEIGHTS_SUBDIR = "pretrained_weights/TripoSG"

    def __init__(
        self,
        model_path: str = None,
        device: str = "cuda",
        dtype: torch.dtype = None,
        num_inference_steps: int = 50,
        guidance_scale: float = 7.5,
        seed: int = 42,
    ):
        """
        Args:
            model_path: Path to the TripoSG weights directory.  If ``None``,
                        the default location used by the official TripoSG repo
                        (``<triposg-repo>/pretrained_weights/TripoSG``) is tried
                        first; if absent, weights are auto-downloaded there.
            device: PyTorch device string ("cuda" or "cpu").
            dtype: Model precision.  Defaults to bfloat16 on Ampere+ GPUs,
                   float16 elsewhere, float32 on CPU.
            num_inference_steps: Diffusion denoising steps (50 is a good balance).
            guidance_scale: Classifier-free guidance scale (7.5 default).
            seed: RNG seed for reproducibility.
        """
        self.model_path = model_path
        self.device = device

        if dtype is None:
            if "cuda" in str(device) and torch.cuda.is_available():
                cap = torch.cuda.get_device_capability()
                dtype = torch.bfloat16 if cap[0] >= 8 else torch.float16
            else:
                dtype = torch.float32
        self.dtype = dtype
        self.num_inference_steps = num_inference_steps
        self.guidance_scale = guidance_scale
        self.seed = seed
        self._pipe = None

    # ── weight management ─────────────────────────────────────────────────

    def _ensure_local_weights(self, triposg_repo_dir: str) -> str:
        """Ensure TripoSG weights exist locally and return the local directory path."""
        from huggingface_hub import snapshot_download

        candidates = []
        if self.model_path:
            candidates.append(self.model_path)
        if triposg_repo_dir:
            candidates.append(os.path.join(triposg_repo_dir, self.DEFAULT_WEIGHTS_SUBDIR))
        candidates.append("/workspace/TripoSG-VGGT_Omega-3D/checkpoints/TripoSG")

        for path in candidates:
            if os.path.isdir(path) and os.listdir(path):
                print(f"[TripoSG] Found weights at {path}")
                return path

        target = candidates[0]
        os.makedirs(target, exist_ok=True)
        print(f"[TripoSG] Downloading {self.HF_MODEL_ID} → {target} ...")
        snapshot_download(self.HF_MODEL_ID, local_dir=target)
        print("[TripoSG] Download complete.")
        return target

    # ── pipeline lifecycle ────────────────────────────────────────────────

    def load(self):
        """Load the TripoSGPipeline (lazy — called automatically by :meth:`generate`)."""
        if self._pipe is not None:
            return

        _repo_candidates = [
            os.path.join(
                os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                "triposg-repo",
            ),
            "/workspace/TripoSG-VGGT_Omega-3D/triposg-repo",
        ]
        _triposg_repo = None
        for _cand in _repo_candidates:
            if os.path.isdir(_cand):
                _triposg_repo = _cand
                if _cand not in sys.path:
                    sys.path.insert(0, _cand)
                break

        try:
            from triposg.pipelines.pipeline_triposg import TripoSGPipeline
        except ImportError as exc:
            raise ImportError(
                "triposg is not importable.  Run final_setup.sh to clone the repo and "
                "set PYTHONPATH, or manually:\n"
                "  git clone https://github.com/VAST-AI-Research/TripoSG.git triposg-repo\n"
                "  export PYTHONPATH=triposg-repo:$PYTHONPATH"
            ) from exc

        local_weights = self._ensure_local_weights(_triposg_repo or "")

        print(f"[TripoSG] Loading pipeline from {local_weights} ...")
        self._pipe = TripoSGPipeline.from_pretrained(local_weights)
        self._pipe = self._pipe.to(self.device, self.dtype)
        print("[TripoSG] Pipeline ready.")

    def unload(self):
        """Delete the pipeline and free GPU memory."""
        if self._pipe is not None:
            del self._pipe
            self._pipe = None
            gc.collect()
            if "cuda" in str(self.device) and torch.cuda.is_available():
                torch.cuda.empty_cache()
            print("[TripoSG] Pipeline unloaded.")

    # ── mesh generation ───────────────────────────────────────────────────

    def generate(self, image: Image.Image) -> "trimesh.Trimesh":
        """
        Generate a 3D mesh from a single PIL image.

        RGBA images are composited onto a white background before inference
        (TripoSG expects an RGB input).

        Args:
            image: Input image (RGB or RGBA).

        Returns:
            ``trimesh.Trimesh`` with the generated mesh (geometry + optional
            per-vertex colour).  Export to .glb with ``mesh.export("out.glb")``.
        """
        import trimesh

        if image.mode == "RGBA":
            bg = Image.new("RGB", image.size, (255, 255, 255))
            bg.paste(image, mask=image.split()[3])
            image = bg
        else:
            image = image.convert("RGB")

        self.load()

        generator = torch.Generator(device=self._pipe.device).manual_seed(self.seed)
        outputs = self._pipe(
            image=image,
            generator=generator,
            num_inference_steps=self.num_inference_steps,
            guidance_scale=self.guidance_scale,
        ).samples[0]

        vertices = outputs[0].astype(np.float32)
        faces = np.ascontiguousarray(outputs[1])

        if len(outputs) > 2 and outputs[2] is not None:
            vertex_colors = outputs[2]
            mesh = trimesh.Trimesh(vertices, faces, vertex_colors=vertex_colors)
        else:
            mesh = trimesh.Trimesh(vertices, faces)

        return mesh

    def generate_from_path(self, image_path: str) -> "trimesh.Trimesh":
        """
        Convenience wrapper — loads the image from *image_path* and calls
        :meth:`generate`.
        """
        image = Image.open(image_path).convert("RGBA")
        return self.generate(image)


# Backward compatibility alias — old code that imports TripoSGTexturizer keeps working.
TripoSGTexturizer = TripoSGMeshBackbone


# ── MVAdapterTexturizer ───────────────────────────────────────────────────────

class MVAdapterTexturizer:
    """
    Texturizes an existing 3D mesh using MV-Adapter (huanngzh/MV-Adapter).

    MV-Adapter is a plug-and-play adapter that adapts Stable Diffusion models to
    geometry-guided multi-view generators.  This class wraps the full texture
    pipeline:

    1. **Multi-view generation** — an image-/text-geometry conditioned pipeline
       renders 6 consistent views of the mesh.
    2. **UV projection** — the multi-view images are un-projected onto the mesh
       UV atlas with inpainting (LaMa) and upscaling (RealESRGAN).

    Two conditioning modes are supported:

    * **Image-conditioned** (:meth:`texturize_with_image`) — provide a reference
      photograph of the object; the adapter generates views matching the photo's
      appearance.  Uses the ``ig2mv`` (image + geometry → multi-view) weights.
    * **Text-conditioned** (:meth:`texturize_with_text`) — provide a text prompt;
      the adapter generates views from scratch.  Uses the ``tg2mv`` (text +
      geometry → multi-view) weights.

    A convenience method :meth:`texturize` dispatches to the appropriate mode.

    Prerequisites (handled by ``final_setup.sh``)::

        git clone https://github.com/huanngzh/MV-Adapter.git mvadapter-repo
        pip install -e mvadapter-repo
        pip install git+https://github.com/NVlabs/nvdiffrast.git
        # checkpoints:
        wget .../RealESRGAN_x2plus.pth -O checkpoints/RealESRGAN_x2plus.pth
        wget .../big-lama.pt           -O checkpoints/big-lama.pt

    Example — image-conditioned::

        tex = MVAdapterTexturizer(device="cuda")
        out_path = tex.texturize_with_image(
            mesh_path="object.glb",
            image=Image.open("object.png"),
            save_dir="outputs",
            save_name="object_textured",
        )
        # → "outputs/object_textured_shaded.glb"

    Example — text-conditioned::

        tex = MVAdapterTexturizer(device="cuda")
        out_path = tex.texturize_with_text(
            mesh_path="object.glb",
            text="a rusty iron robot",
            save_dir="outputs",
            save_name="object_textured",
        )
    """

    MV_ADAPTER_REPO_URL = "https://github.com/huanngzh/MV-Adapter.git"
    # stabilityai/stable-diffusion-2-1-base was removed from the Hub; use a diffusers mirror.
    SD21_BASE_MODEL_DEFAULT = "Manojb/stable-diffusion-2-1-base"
    SD21_DIFFUSERS_ALLOW_PATTERNS = (
        "model_index.json",
        "scheduler/*",
        "text_encoder/*",
        "tokenizer/*",
        "unet/*",
        "vae/*",
        "feature_extractor/*",
    )
    REALESRGAN_URL = (
        "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/"
        "RealESRGAN_x2plus.pth"
    )
    LAMA_URL = (
        "https://github.com/Sanster/models/releases/download/add_big_lama/big-lama.pt"
    )

    def __init__(
        self,
        variant: str = "sdxl",
        device: str = "cuda",
        num_views: int = 6,
        num_inference_steps: int = 50,
        guidance_scale_image: float = 3.0,
        guidance_scale_text: float = 7.0,
        reference_conditioning_scale: float = 1.0,
        seed: int = -1,
        checkpoints_dir: str = None,
        mvadapter_repo_dir: str = None,
        sd21_base_model: str = None,
    ):
        """
        Args:
            variant: Base diffusion model.  ``"sdxl"`` (default, higher quality,
                     768 px, ~16 GB VRAM) or ``"sd21"`` (lower resources, 512 px,
                     <10 GB VRAM).
            device: PyTorch device string ("cuda" or "cpu").
            num_views: Number of views to generate (default 6).
            num_inference_steps: Diffusion steps for multi-view generation (50).
            guidance_scale_image: CFG scale for image-conditioned generation (3.0).
            guidance_scale_text: CFG scale for text-conditioned generation (7.0).
            reference_conditioning_scale: How strongly the reference image steers
                the generation (1.0 = full control).
            seed: RNG seed.  ``-1`` means random.
            checkpoints_dir: Directory containing ``RealESRGAN_x2plus.pth`` and
                             ``big-lama.pt``.  Defaults to the ``checkpoints/``
                             folder inside this repository.
            mvadapter_repo_dir: Path to the cloned MV-Adapter repository.
                                Auto-detected from common locations if ``None``.
            sd21_base_model: HuggingFace repo ID or local diffusers directory for
                             SD2.1 (used when ``variant="sd21"``).  Defaults to
                             ``MVADAPTER_SD21_BASE_MODEL`` env var, then auto-downloads
                             to ``checkpoints/stable-diffusion-2-1-base`` on first use.
        """
        assert variant in ("sdxl", "sd21"), f"variant must be 'sdxl' or 'sd21', got {variant!r}"
        self.variant = variant
        self.device = device
        self.num_views = num_views
        self.num_inference_steps = num_inference_steps
        self.guidance_scale_image = guidance_scale_image
        self.guidance_scale_text = guidance_scale_text
        self.reference_conditioning_scale = reference_conditioning_scale
        self.seed = seed

        # Resolve checkpoints directory
        if checkpoints_dir is None:
            _repo_root = os.path.dirname(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            )
            checkpoints_dir = os.path.join(_repo_root, "checkpoints")
        self.checkpoints_dir = checkpoints_dir
        self.sd21_base_model = self._resolve_sd21_base_model(sd21_base_model)
        self.upscaler_ckpt = os.path.join(checkpoints_dir, "RealESRGAN_x2plus.pth")
        self.inpaint_ckpt  = os.path.join(checkpoints_dir, "big-lama.pt")

        # Resolve MVAdapter repo
        self._mvadapter_repo = mvadapter_repo_dir
        self._mv_pipe = None
        self._tex_pipe = None

    @classmethod
    def default_sd21_local_dir(cls, checkpoints_dir: str = None) -> str:
        """Return the default on-disk path for the SD2.1 diffusers checkpoint."""
        if checkpoints_dir is None:
            _repo_root = os.path.dirname(
                os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            )
            checkpoints_dir = os.path.join(_repo_root, "checkpoints")
        return os.path.join(checkpoints_dir, "stable-diffusion-2-1-base")

    @classmethod
    def _is_local_diffusers_dir(cls, path: str) -> bool:
        return os.path.isfile(os.path.join(path, "model_index.json"))

    def _resolve_sd21_base_model(self, sd21_base_model: str = None) -> str:
        """
        Pick the SD2.1 base model source (local path or HF repo id).

        Priority:
          1. explicit argument
          2. MVADAPTER_SD21_BASE_MODEL env var
          3. local checkpoints/stable-diffusion-2-1-base (if model_index.json exists)
          4. community HF mirror (:data:`SD21_BASE_MODEL_DEFAULT`) — downloaded on first use
        """
        if sd21_base_model:
            return sd21_base_model

        env_model = os.environ.get("MVADAPTER_SD21_BASE_MODEL")
        if env_model:
            return env_model

        local_dir = self.default_sd21_local_dir(self.checkpoints_dir)
        if self._is_local_diffusers_dir(local_dir):
            return local_dir

        return self.SD21_BASE_MODEL_DEFAULT

    def _ensure_sd21_base_model(self) -> None:
        """
        Ensure the SD2.1 diffusers checkpoint is available locally.

        stabilityai/stable-diffusion-2-1-base was removed from Hugging Face; when
        ``self.sd21_base_model`` is a Hub repo id (or the default mirror), this
        downloads the diffusers components into
        ``checkpoints/stable-diffusion-2-1-base/``.
        """
        if self.variant != "sd21":
            return

        if self._is_local_diffusers_dir(self.sd21_base_model):
            return

        if os.path.isdir(self.sd21_base_model):
            raise FileNotFoundError(
                f"SD2.1 base model directory is missing model_index.json: "
                f"{self.sd21_base_model}"
            )

        local_dir = self.default_sd21_local_dir(self.checkpoints_dir)
        marker = os.path.join(local_dir, "model_index.json")
        if os.path.isfile(marker):
            self.sd21_base_model = local_dir
            return

        hf_repo = self.sd21_base_model or self.SD21_BASE_MODEL_DEFAULT
        os.makedirs(local_dir, exist_ok=True)

        try:
            from huggingface_hub import snapshot_download
        except ImportError as exc:
            raise RuntimeError(
                "huggingface_hub is required to download the SD2.1 base model. "
                "Install it with: pip install huggingface_hub"
            ) from exc

        print(f"[MVAdapter] Downloading SD2.1 base model from {hf_repo} → {local_dir} ...")
        snapshot_download(
            repo_id=hf_repo,
            local_dir=local_dir,
            allow_patterns=list(self.SD21_DIFFUSERS_ALLOW_PATTERNS),
        )

        if not os.path.isfile(marker):
            raise RuntimeError(
                f"SD2.1 download finished but model_index.json is missing in {local_dir}"
            )

        self.sd21_base_model = local_dir
        print(f"[MVAdapter] SD2.1 base model ready → {local_dir}")

    # ── MVAdapter repo discovery ───────────────────────────────────────────

    def _ensure_mvadapter_repo(self) -> str:
        """
        Locate or clone the MV-Adapter repository and add it to sys.path.
        Returns the repository root directory.
        """
        if self._mvadapter_repo and os.path.isdir(self._mvadapter_repo):
            repo = self._mvadapter_repo
        else:
            _this_file = os.path.abspath(__file__)
            _repo_root = os.path.dirname(os.path.dirname(os.path.dirname(_this_file)))
            candidates = [
                os.path.join(_repo_root, "mvadapter-repo"),
                "/workspace/TripoSG-VGGT_Omega-3D/mvadapter-repo",
            ]
            repo = None
            for cand in candidates:
                if os.path.isdir(cand):
                    repo = cand
                    break

            if repo is None:
                raise RuntimeError(
                    "MV-Adapter repository not found. Run final_setup.sh, or:\n"
                    "  git clone https://github.com/huanngzh/MV-Adapter.git mvadapter-repo\n"
                    "  pip install -e mvadapter-repo"
                )

        if repo not in sys.path:
            sys.path.insert(0, repo)
        self._mvadapter_repo = repo
        return repo

    def _ensure_checkpoints(self):
        """Download RealESRGAN and LaMa checkpoints if missing."""
        import urllib.request

        os.makedirs(self.checkpoints_dir, exist_ok=True)

        if not os.path.isfile(self.upscaler_ckpt):
            print(f"[MVAdapter] Downloading RealESRGAN → {self.upscaler_ckpt} ...")
            urllib.request.urlretrieve(self.REALESRGAN_URL, self.upscaler_ckpt)
            print("[MVAdapter] RealESRGAN download complete.")

        if not os.path.isfile(self.inpaint_ckpt):
            print(f"[MVAdapter] Downloading LaMa → {self.inpaint_ckpt} ...")
            urllib.request.urlretrieve(self.LAMA_URL, self.inpaint_ckpt)
            print("[MVAdapter] LaMa download complete.")

    # ── pipeline loading ───────────────────────────────────────────────────

    def _load_mv_pipeline_image(self):
        """Load the image-geometry → multi-view pipeline (ig2mv)."""
        self._ensure_mvadapter_repo()
        self._ensure_sd21_base_model()

        if self.variant == "sdxl":
            from scripts.inference_ig2mv_sdxl import prepare_pipeline
            base_model = "stabilityai/stable-diffusion-xl-base-1.0"
            vae_model  = "madebyollin/sdxl-vae-fp16-fix"
        else:
            from scripts.inference_ig2mv_sd import prepare_pipeline
            base_model = self.sd21_base_model
            vae_model  = None

        print(f"[MVAdapter] Loading ig2mv pipeline ({self.variant}, base={base_model}) ...")
        pipe = prepare_pipeline(
            base_model=base_model,
            vae_model=vae_model,
            unet_model=None,
            lora_model=None,
            adapter_path="huanngzh/mv-adapter",
            scheduler=None,
            num_views=self.num_views,
            device=self.device,
            dtype=torch.float16,
        )
        print("[MVAdapter] ig2mv pipeline ready.")
        return pipe

    def _load_mv_pipeline_text(self):
        """Load the text-geometry → multi-view pipeline (tg2mv)."""
        self._ensure_mvadapter_repo()
        self._ensure_sd21_base_model()

        if self.variant == "sdxl":
            from scripts.inference_tg2mv_sdxl import prepare_pipeline
            base_model = "stabilityai/stable-diffusion-xl-base-1.0"
            vae_model  = "madebyollin/sdxl-vae-fp16-fix"
        else:
            from scripts.inference_tg2mv_sd import prepare_pipeline
            base_model = self.sd21_base_model
            vae_model  = None

        print(f"[MVAdapter] Loading tg2mv pipeline ({self.variant}, base={base_model}) ...")
        pipe = prepare_pipeline(
            base_model=base_model,
            vae_model=vae_model,
            unet_model=None,
            lora_model=None,
            adapter_path="huanngzh/mv-adapter",
            scheduler=None,
            num_views=self.num_views,
            device=self.device,
            dtype=torch.float16,
        )
        print("[MVAdapter] tg2mv pipeline ready.")
        return pipe

    def _load_texture_pipeline(self):
        """Load the UV-projection TexturePipeline."""
        self._ensure_checkpoints()
        from mvadapter.pipelines.pipeline_texture import TexturePipeline

        print("[MVAdapter] Loading TexturePipeline ...")
        tex_pipe = TexturePipeline(
            upscaler_ckpt_path=self.upscaler_ckpt,
            inpaint_ckpt_path=self.inpaint_ckpt,
            device=self.device,
        )
        print("[MVAdapter] TexturePipeline ready.")
        return tex_pipe

    def unload(self):
        """Delete all loaded pipelines and free GPU memory."""
        for attr in ("_mv_pipe", "_tex_pipe"):
            obj = getattr(self, attr, None)
            if obj is not None:
                setattr(self, attr, None)
                del obj
        gc.collect()
        if "cuda" in str(self.device) and torch.cuda.is_available():
            torch.cuda.empty_cache()
        print("[MVAdapter] Pipelines unloaded.")

    # ── texturizing ────────────────────────────────────────────────────────

    def texturize_with_image(
        self,
        mesh_path: str,
        image,
        text: str = "high quality",
        save_dir: str = "outputs",
        save_name: str = "textured",
        preprocess_mesh: bool = False,
        remove_bg: bool = False,
    ) -> str:
        """
        Texturize *mesh_path* guided by a reference *image*.

        Args:
            mesh_path: Path to the input mesh (.glb).
            image: Reference image as a file path or PIL.Image.
            text: Text hint used alongside the image (default: "high quality").
            save_dir: Directory where outputs are saved.
            save_name: Base name for saved files (no extension).
            preprocess_mesh: Whether MVAdapter should re-mesh / normalise the mesh.
            remove_bg: Whether to remove the background from the reference image
                       using BiRefNet before using it.

        Returns:
            Path to the shaded output mesh (``<save_dir>/<save_name>_shaded.glb``).
        """
        self._ensure_mvadapter_repo()

        if self.variant == "sdxl":
            from scripts.inference_ig2mv_sdxl import run_pipeline
            height = width = 768
            uv_size = 4096
        else:
            from scripts.inference_ig2mv_sd import run_pipeline
            height = width = 512
            uv_size = 2048

        from mvadapter.pipelines.pipeline_texture import ModProcessConfig, TexturePipeline
        from mvadapter.utils import make_image_grid

        os.makedirs(save_dir, exist_ok=True)

        # Lazy-load multi-view pipeline
        if self._mv_pipe is None:
            self._mv_pipe = self._load_mv_pipeline_image()

        # Optional background removal
        remove_bg_fn = None
        if remove_bg:
            from torchvision import transforms
            from transformers import AutoModelForImageSegmentation

            birefnet = AutoModelForImageSegmentation.from_pretrained(
                "ZhengPeng7/BiRefNet", trust_remote_code=True
            )
            birefnet.to(self.device)
            _tf = transforms.Compose([
                transforms.Resize((1024, 1024)),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
            ])

            def _remove_bg(img):
                from scripts.inference_ig2mv_sdxl import remove_bg as _rb
                return _rb(img, birefnet, _tf, self.device)

            remove_bg_fn = _remove_bg

        print("[MVAdapter] Generating multi-view images (image-conditioned) ...")
        images, _, _, _ = run_pipeline(
            self._mv_pipe,
            mesh_path=mesh_path,
            num_views=self.num_views,
            text=text,
            image=image,
            height=height,
            width=width,
            num_inference_steps=self.num_inference_steps,
            guidance_scale=self.guidance_scale_image,
            seed=self.seed,
            reference_conditioning_scale=self.reference_conditioning_scale,
            negative_prompt="watermark, ugly, deformed, noisy, blurry, low contrast",
            device=self.device,
            remove_bg_fn=remove_bg_fn,
        )
        mv_path = os.path.join(save_dir, f"{save_name}.png")
        make_image_grid(images, rows=1).save(mv_path)
        print(f"[MVAdapter] Multi-view grid saved → {mv_path}")

        torch.cuda.empty_cache()

        # Lazy-load texture pipeline
        if self._tex_pipe is None:
            self._tex_pipe = self._load_texture_pipeline()

        print("[MVAdapter] Projecting textures onto mesh ...")
        out = self._tex_pipe(
            mesh_path=mesh_path,
            save_dir=save_dir,
            save_name=save_name,
            uv_unwarp=True,
            preprocess_mesh=preprocess_mesh,
            uv_size=uv_size,
            rgb_path=mv_path,
            rgb_process_config=ModProcessConfig(view_upscale=True, inpaint_mode="view"),
            # Must match the official texture_i2tex.py convention: pass angles with -90
            # already applied.  TexturePipeline applies another -90 internally AND loads
            # the mesh with front_x_to_y=True (90° rotation).  The double -90 offsets
            # the camera azimuths to compensate for that mesh rotation, so each view
            # lands on exactly the same mesh face it was generated from.
            camera_azimuth_deg=[x - 90 for x in [0, 90, 180, 270, 180, 180]],
        )
        shaded_path = out.shaded_model_save_path
        print(f"[MVAdapter] Textured mesh saved → {shaded_path}")
        return shaded_path

    def texturize_with_text(
        self,
        mesh_path: str,
        text: str,
        save_dir: str = "outputs",
        save_name: str = "textured",
        preprocess_mesh: bool = False,
    ) -> str:
        """
        Texturize *mesh_path* guided by a *text* prompt.

        Args:
            mesh_path: Path to the input mesh (.glb).
            text: Text description of the desired appearance.
            save_dir: Directory where outputs are saved.
            save_name: Base name for saved files (no extension).
            preprocess_mesh: Whether MVAdapter should re-mesh / normalise the mesh.

        Returns:
            Path to the shaded output mesh (``<save_dir>/<save_name>_shaded.glb``).
        """
        self._ensure_mvadapter_repo()

        if self.variant == "sdxl":
            from scripts.inference_tg2mv_sdxl import run_pipeline
            height = width = 768
            uv_size = 4096
        else:
            from scripts.inference_tg2mv_sd import run_pipeline
            height = width = 512
            uv_size = 2048

        from mvadapter.pipelines.pipeline_texture import ModProcessConfig, TexturePipeline
        from mvadapter.utils import make_image_grid

        os.makedirs(save_dir, exist_ok=True)

        # Lazy-load multi-view pipeline
        if self._mv_pipe is None:
            self._mv_pipe = self._load_mv_pipeline_text()

        print("[MVAdapter] Generating multi-view images (text-conditioned) ...")
        images, _, _ = run_pipeline(
            self._mv_pipe,
            mesh_path=mesh_path,
            num_views=self.num_views,
            text=text,
            height=height,
            width=width,
            num_inference_steps=self.num_inference_steps,
            guidance_scale=self.guidance_scale_text,
            seed=self.seed,
            negative_prompt="watermark, ugly, deformed, noisy, blurry, low contrast",
            device=self.device,
        )
        mv_path = os.path.join(save_dir, f"{save_name}.png")
        make_image_grid(images, rows=1).save(mv_path)
        print(f"[MVAdapter] Multi-view grid saved → {mv_path}")

        torch.cuda.empty_cache()

        # Lazy-load texture pipeline
        if self._tex_pipe is None:
            self._tex_pipe = self._load_texture_pipeline()

        print("[MVAdapter] Projecting textures onto mesh ...")
        out = self._tex_pipe(
            mesh_path=mesh_path,
            save_dir=save_dir,
            save_name=save_name,
            uv_unwarp=True,
            preprocess_mesh=preprocess_mesh,
            uv_size=uv_size,
            rgb_path=mv_path,
            rgb_process_config=ModProcessConfig(view_upscale=True, inpaint_mode="view"),
            # Must match the official texture_t2tex.py convention: pass angles with -90
            # already applied.  TexturePipeline applies another -90 internally AND loads
            # the mesh with front_x_to_y=True (90° rotation).  The double -90 offsets
            # the camera azimuths to compensate for that mesh rotation, so each view
            # lands on exactly the same mesh face it was generated from.
            camera_azimuth_deg=[x - 90 for x in [0, 90, 180, 270, 180, 180]],
        )
        shaded_path = out.shaded_model_save_path
        print(f"[MVAdapter] Textured mesh saved → {shaded_path}")
        return shaded_path

    def texturize(
        self,
        mesh_path: str,
        image=None,
        text: str = None,
        save_dir: str = "outputs",
        save_name: str = "textured",
        **kwargs,
    ) -> str:
        """
        Dispatch to :meth:`texturize_with_image` or :meth:`texturize_with_text`.

        Exactly one of *image* or *text* must be supplied.

        Args:
            mesh_path: Path to the input mesh (.glb).
            image: Reference image (file path or PIL.Image) for image-conditioned mode.
            text:  Text prompt for text-conditioned mode.
            save_dir: Output directory.
            save_name: Base output filename (no extension).
            **kwargs: Forwarded to the respective ``texturize_with_*`` method.

        Returns:
            Path to the shaded output .glb.
        """
        if image is not None and text is not None:
            # Both given — use image-conditioned with text as hint
            return self.texturize_with_image(
                mesh_path, image=image, text=text,
                save_dir=save_dir, save_name=save_name, **kwargs,
            )
        elif image is not None:
            return self.texturize_with_image(
                mesh_path, image=image,
                save_dir=save_dir, save_name=save_name, **kwargs,
            )
        elif text is not None:
            return self.texturize_with_text(
                mesh_path, text=text,
                save_dir=save_dir, save_name=save_name, **kwargs,
            )
        else:
            raise ValueError("Provide at least one of 'image' or 'text' to texturize().")


# ── MeshGenerator ─────────────────────────────────────────────────────────────

class MeshGenerator:
    """
    Generates 3D meshes from 2D images.

    Shape backbone: Hunyuan3D-2 (always generates the base geometry).

    Three texturizing backends are supported:

    * ``"hunyuan"`` (default) — Hunyuan3D-2 two-step pipeline:
      :meth:`generate_mesh` creates the shape, then
      :meth:`generate_painted_mesh` paints UV textures with
      ``Hunyuan3DPaintPipeline``.

    * ``"mvadapter"`` — MV-Adapter geometry-guided texturizing:
      :meth:`generate_mesh` creates and **saves** the Hunyuan3D shape; then
      :meth:`generate_painted_mesh` runs ``MVAdapterTexturizer`` on that saved
      .glb to produce a UV-textured mesh.  Call :meth:`save_mesh` *before*
      :meth:`generate_painted_mesh` when using this backend (so the mesh file
      path is available), or pass *mesh_path* explicitly.

    * ``"triposg"`` — TripoSG one-step mesh backbone:
      :meth:`generate_painted_mesh` runs ``TripoSGMeshBackbone`` on the original
      image and returns a fully coloured mesh in one shot (calling
      :meth:`generate_mesh` first is not required).
    """

    def __init__(
        self,
        image_path: str,
        pipeline_flow=None,
        pipeline_paint=None,
        texture_backend: str = "hunyuan",
        # TripoSG backbone options
        triposg_model_path: str = None,
        triposg_num_steps: int = 50,
        triposg_guidance_scale: float = 7.5,
        triposg_seed: int = 42,
        # MVAdapter texturizer options
        mvadapter_variant: str = "sdxl",
        mvadapter_num_steps: int = 50,
        mvadapter_guidance_scale_image: float = 3.0,
        mvadapter_guidance_scale_text: float = 7.0,
        mvadapter_seed: int = -1,
        mvadapter_checkpoints_dir: str = None,
        mvadapter_repo_dir: str = None,
    ):
        """
        Args:
            image_path: Path to the input image.
            pipeline_flow: Pre-loaded ``Hunyuan3DDiTFlowMatchingPipeline``.
                           Loaded lazily from ``tencent/Hunyuan3D-2`` if
                           ``None`` and ``texture_backend != "triposg"``.
            pipeline_paint: Pre-loaded ``Hunyuan3DPaintPipeline``.
                            Loaded lazily if ``None`` and
                            ``texture_backend == "hunyuan"``.
            texture_backend: ``"hunyuan"``, ``"mvadapter"``, or ``"triposg"``.
            triposg_model_path: Local path to TripoSG weights.
            triposg_num_steps: TripoSG denoising steps (default 50).
            triposg_guidance_scale: TripoSG guidance scale (default 7.5).
            triposg_seed: TripoSG RNG seed (default 42).
            mvadapter_variant: ``"sdxl"`` or ``"sd21"`` (default ``"sdxl"``).
            mvadapter_num_steps: MVAdapter multi-view denoising steps (50).
            mvadapter_guidance_scale_image: CFG for image-conditioned mode (3.0).
            mvadapter_guidance_scale_text: CFG for text-conditioned mode (7.0).
            mvadapter_seed: MVAdapter RNG seed (-1 = random).
            mvadapter_checkpoints_dir: Directory with RealESRGAN and LaMa weights.
            mvadapter_repo_dir: Path to the cloned MV-Adapter repo.
        """
        self.image = Image.open(image_path).convert("RGBA")
        self.image_path = image_path
        self.mesh = None
        self._saved_mesh_path = None   # set by save_mesh(); needed by MVAdapter
        self.painted_mesh = None
        self.texture_backend = texture_backend

        # TripoSG mesh backbone (lazy-loaded on first use)
        self._triposg = TripoSGMeshBackbone(
            model_path=triposg_model_path,
            num_inference_steps=triposg_num_steps,
            guidance_scale=triposg_guidance_scale,
            seed=triposg_seed,
        )

        # MVAdapter texturizer (lazy-loaded on first use)
        self._mvadapter = MVAdapterTexturizer(
            variant=mvadapter_variant,
            num_inference_steps=mvadapter_num_steps,
            guidance_scale_image=mvadapter_guidance_scale_image,
            guidance_scale_text=mvadapter_guidance_scale_text,
            seed=mvadapter_seed,
            checkpoints_dir=mvadapter_checkpoints_dir,
            mvadapter_repo_dir=mvadapter_repo_dir,
        )

        # Hunyuan pipelines — only load when using the hunyuan/mvadapter backend
        if texture_backend != "triposg":
            if pipeline_flow is None:
                self.pipeline_flow = Hunyuan3DDiTFlowMatchingPipeline.from_pretrained(
                    "tencent/Hunyuan3D-2"
                )
            else:
                self.pipeline_flow = pipeline_flow

            if pipeline_paint is None and texture_backend == "hunyuan":
                self.pipeline_paint = Hunyuan3DPaintPipeline.from_pretrained(
                    "tencent/Hunyuan3D-2"
                )
            else:
                self.pipeline_paint = pipeline_paint
        else:
            self.pipeline_flow = pipeline_flow
            self.pipeline_paint = pipeline_paint

    # ── mesh generation ───────────────────────────────────────────────────

    def generate_mesh(self):
        """
        Generate the base (untextured) 3D mesh from the image using Hunyuan3D-2.

        Not required when ``texture_backend="triposg"`` since TripoSG
        generates both geometry and texture in one step.
        """
        if self.pipeline_flow is None:
            raise ValueError(
                "pipeline_flow is required for Hunyuan mesh generation. "
                "Pass one explicitly or set texture_backend='hunyuan'/'mvadapter'."
            )
        self.mesh = self.pipeline_flow(image=self.image)[0]
        return self.mesh

    def generate_painted_mesh(self, backend: str = None, mesh_path: str = None,
                               text: str = None, save_dir: str = None,
                               save_name: str = None):
        """
        Generate the textured mesh.

        Args:
            backend: Override the instance-level ``texture_backend`` for this
                     call.  One of ``"hunyuan"``, ``"mvadapter"``, or ``"triposg"``.
            mesh_path: Path to the saved base mesh .glb.  Required when
                       ``backend="mvadapter"`` and :meth:`save_mesh` has not yet
                       been called.  Ignored for other backends.
            text: Optional text prompt for MVAdapter text-conditioned mode.
                  If ``None``, the reference image (``self.image_path``) is used.
            save_dir: Output directory for MVAdapter results.  Ignored for other
                      backends.
            save_name: Base filename for MVAdapter output (no extension).

        Returns:
            The textured mesh object or path depending on the backend:
            - ``"hunyuan"`` → whatever ``Hunyuan3DPaintPipeline`` returns
            - ``"triposg"`` → ``trimesh.Trimesh``
            - ``"mvadapter"`` → str path to the shaded .glb
        """
        use_backend = backend if backend is not None else self.texture_backend

        if use_backend == "triposg":
            return self._generate_with_triposg()
        elif use_backend == "mvadapter":
            return self._generate_with_mvadapter(
                mesh_path=mesh_path, text=text,
                save_dir=save_dir, save_name=save_name,
            )
        else:
            return self._generate_with_hunyuan()

    def _generate_with_hunyuan(self):
        """Internal — run Hunyuan3DPaintPipeline on the base mesh."""
        if self.mesh is None:
            raise ValueError(
                "Call generate_mesh() before generate_painted_mesh() "
                "when using the Hunyuan backend."
            )
        if self.pipeline_paint is None:
            raise ValueError(
                "pipeline_paint is required for Hunyuan texturing. "
                "Pass one explicitly or use texture_backend='hunyuan'."
            )
        self.painted_mesh = self.pipeline_paint(self.mesh, image=self.image)
        return self.painted_mesh

    def _generate_with_triposg(self):
        """
        Internal — run TripoSGMeshBackbone on the original image to produce a
        complete geometry mesh (bypasses the Hunyuan shape generation step).
        """
        print("[MeshGenerator] Generating mesh with TripoSG backbone ...")
        self.painted_mesh = self._triposg.generate(self.image)
        return self.painted_mesh

    def _generate_with_mvadapter(self, mesh_path=None, text=None,
                                  save_dir=None, save_name=None):
        """
        Internal — run MVAdapterTexturizer on the saved Hunyuan3D base mesh.

        The Hunyuan3D base mesh must have been saved first (via :meth:`save_mesh`
        or by passing *mesh_path* explicitly).
        """
        # Resolve mesh file path
        resolved_path = mesh_path or self._saved_mesh_path
        if not resolved_path:
            raise ValueError(
                "MVAdapter texturizing requires the base mesh to be saved first. "
                "Call save_mesh(path) before generate_painted_mesh(), or pass "
                "mesh_path explicitly to generate_painted_mesh()."
            )
        if not os.path.isfile(resolved_path):
            raise FileNotFoundError(
                f"Mesh file not found: {resolved_path}\n"
                "Make sure save_mesh() was called successfully before texturizing."
            )

        # Resolve save_dir / save_name from mesh path if not specified
        if save_dir is None:
            save_dir = os.path.dirname(resolved_path) or "."
        if save_name is None:
            stem = os.path.splitext(os.path.basename(resolved_path))[0]
            save_name = f"{stem}_mvadapter"

        print(f"[MeshGenerator] Texturizing with MVAdapter ({'text' if text else 'image'} mode) ...")
        shaded_path = self._mvadapter.texturize(
            mesh_path=resolved_path,
            image=None if text else self.image,
            text=text,
            save_dir=save_dir,
            save_name=save_name,
        )
        self.painted_mesh = shaded_path
        return shaded_path

    # ── save helpers ──────────────────────────────────────────────────────

    def save_mesh(self, path: str):
        """Save the base (untextured) mesh to *path* and record the path."""
        if self.mesh is None:
            raise ValueError("No mesh to save.  Call generate_mesh() first.")
        self.mesh.export(path)
        self._saved_mesh_path = path

    def save_painted_mesh(self, path: str):
        """
        Save the textured mesh to *path*.

        For ``"mvadapter"`` backend, the mesh is already saved by the texturizer
        and this method copies / renames it if the desired *path* differs from
        the auto-generated one.
        """
        if self.painted_mesh is None:
            raise ValueError(
                "No painted mesh to save.  Call generate_painted_mesh() first."
            )
        if isinstance(self.painted_mesh, str):
            # MVAdapter already saved the file; rename if needed
            if os.path.abspath(self.painted_mesh) != os.path.abspath(path):
                import shutil
                shutil.move(self.painted_mesh, path)
                self.painted_mesh = path
                print(f"[MeshGenerator] Textured mesh moved → {path}")
            else:
                print(f"[MeshGenerator] Textured mesh already at {path}")
        else:
            self.painted_mesh.export(path)


# ── Renderer ─────────────────────────────────────────────────────────────────

class Renderer:
    """
    Renders 3D meshes loaded from .glb files using PyTorch3D.
    """

    def __init__(self, mesh_path: str, device="cuda"):
        """
        Args:
            mesh_path: Path to the mesh file (.glb format).
            device: PyTorch device string ('cuda' or 'cpu').
        """
        self.device = device
        self.mesh = None
        self.io = None
        self.image_size = None
        self.load_mesh(mesh_path)

    def load_mesh(self, path: str):
        """Load a mesh from *path*."""
        self.io = IO()
        self.io.register_meshes_format(MeshGlbFormat())
        self.mesh = self.io.load_mesh(path, include_textures=True).to(self.device)

    def get_R_T_pytorch(self, R, T):
        """
        Convert OpenCV [R | T] to PyTorch3D camera convention.

        Args:
            R: (N, 3, 3) rotation tensor.
            T: (N, 3, 1) or (N, 3) translation tensor.

        Returns:
            (R_pytorch3d, T_pytorch3d)
        """
        R_pytorch3d = R.clone().permute(0, 2, 1)
        T_pytorch3d = T.clone().squeeze(-1) if T.dim() == 3 else T.clone()

        R_pytorch3d[:, :, :2] *= -1
        T_pytorch3d[:, :2] *= -1

        return R_pytorch3d, T_pytorch3d

    def get_pytorch3d_camera(self, R_pytorch3d, T_pytorch3d, focal_length, principal_point):
        """
        Build a ``PerspectiveCameras`` object from PyTorch3D-convention matrices.
        """
        return PerspectiveCameras(
            device=self.device,
            R=R_pytorch3d,
            T=T_pytorch3d,
            focal_length=focal_length,
            principal_point=principal_point,
            image_size=(self.image_size,),
            in_ndc=False,
        )

    def render(
        self,
        image_size,
        R,
        T,
        K=None,
        focal_length=None,
        principal_point=None,
        blur_radius: float = 0.0,
        location=((0.0, 0.0, -3.0),),
    ):
        """
        Render the mesh with specified camera parameters.

        Args:
            image_size: Output image size (int or (H, W) tuple).
            R: Rotation matrix (numpy or tensor, 3×3 or N×3×3).
            T: Translation vector (numpy or tensor, (3,), (3,1), or N×3).
            K: Optional 3×3 intrinsic matrix.  If given, *focal_length* and
               *principal_point* are derived from it.
            focal_length: Overrides default if *K* is ``None``.
            principal_point: Overrides default if *K* is ``None``.
            blur_radius: Soft-rasterization blur radius.
            location: Light source position(s).

        Returns:
            Rendered RGBA image tensor of shape (1, H, W, 4).
        """
        if isinstance(image_size, (list, tuple)):
            self.image_size = tuple(image_size)
        else:
            self.image_size = (image_size, image_size)

        if K is not None:
            focal_length = torch.tensor(
                [[K[0, 0], K[1, 1]]], device=self.device, dtype=torch.float32
            )
            principal_point = torch.tensor(
                [[K[0, 2], K[1, 2]]], device=self.device, dtype=torch.float32
            )
        else:
            if focal_length is None:
                focal_length = torch.tensor(
                    [[self.image_size[0], self.image_size[1]]],
                    device=self.device,
                    dtype=torch.float32,
                )
            if principal_point is None:
                principal_point = torch.tensor(
                    [[self.image_size[0] / 2, self.image_size[1] / 2]],
                    device=self.device,
                    dtype=torch.float32,
                )

        if isinstance(R, np.ndarray):
            R = torch.from_numpy(R).to(self.device).float()
        if isinstance(T, np.ndarray):
            T = torch.from_numpy(T).to(self.device).float()

        if R.dim() == 2:
            R = R.unsqueeze(0)
        if T.dim() in (1, 2):
            T = T.unsqueeze(0)

        R_pytorch3d, T_pytorch3d = self.get_R_T_pytorch(R, T)
        cameras = self.get_pytorch3d_camera(R_pytorch3d, T_pytorch3d, focal_length, principal_point)

        faces_per_pixel = 5 if blur_radius > 0 else 1
        raster_settings = RasterizationSettings(
            image_size=self.image_size,
            blur_radius=blur_radius,
            faces_per_pixel=faces_per_pixel,
        )
        rasterizer = MeshRasterizer(cameras=cameras, raster_settings=raster_settings)

        lights = PointLights(device=self.device, location=[list(location[0])])
        shader = SoftPhongShader(
            device=self.device,
            cameras=cameras,
            lights=lights,
            blend_params=BlendParams(background_color=(1.0, 1.0, 1.0)),
        )

        renderer = MeshRenderer(rasterizer=rasterizer, shader=shader)
        return renderer(self.mesh)
